#!/bin/bash
# ==============================================================================
# Font Build Script
#
# 生成前端所需的字体文件:
# - Material Symbols Outlined 子集化 (仅保留 icons.txt 列出的图标)
#
# icons.txt 是图标清单的唯一来源:
# - src/config/icon-codepoints.ts (含 IconName 类型) 由本脚本读取 icons.txt 生成;
# - 源码里的图标名交给 TypeScript 校验: MsIcon / icon prop 的类型为 IconName,
#   用了清单外的名字会在编辑器 / vue-tsc 报错, 因此本脚本不再从源码提取图标名
#   (iconMap / 变量传递等动态引用无法可靠提取, 静态 grep 会误报);
# - 更新图标清单后必须重跑本脚本, 否则字体子集与 codepoints 会不同步。
#
# 输出: frontend/public/fonts/MaterialSymbolsOutlined.woff2
#       frontend/src/config/icon-codepoints.ts
# ==============================================================================

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FONTS_DIR="$SCRIPT_DIR/public/fonts"
SRC_DIR="$SCRIPT_DIR/src"
ICONS_FILE="$SCRIPT_DIR/icons.txt"

echo "=== Font Build ==="

# ── 1. 读取图标清单 ──
if [ ! -f "$ICONS_FILE" ]; then
    echo "[ERROR] 找不到图标清单: $ICONS_FILE" >&2
    exit 1
fi

ICONS_TMP="/tmp/ms-icons-list.txt"
# 注释/空行过滤后可能没有剩余行, grep 会以 1 退出; pipefail 下必须放行,
# 否则走不到下面"清单为空"的友好报错 (全注释文件会直接静默中断)
grep -v '^[[:space:]]*#' "$ICONS_FILE" | grep -v '^[[:space:]]*$' | tr -d '\r' | sort -u > "$ICONS_TMP" || true
ICON_COUNT=$(grep -c . "$ICONS_TMP" || true)
if [ "$ICON_COUNT" -eq 0 ]; then
    echo "[ERROR] icons.txt 里没有任何图标名 (只有注释或空行?)" >&2
    exit 1
fi
echo ">>> [1/2] icons.txt: ${ICON_COUNT} icons"

# ── 2. Material Symbols Outlined 子集化 ──
echo ">>> [2/2] Material Symbols subset..."

MS_FULL="/tmp/MaterialSymbolsOutlined-full.woff2"
MS_TTF="/tmp/MaterialSymbolsOutlined-full.ttf"
MS_OUTPUT="$FONTS_DIR/MaterialSymbolsOutlined.woff2"

CODEPOINTS_URL="https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints"
FONT_URL="https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.woff2"

# 下载完整字体和 codepoints 映射 (如果已在提取步骤下载则复用)
wget -q -O "$MS_FULL" "$FONT_URL"
CP_FILE="/tmp/ms-codepoints.txt"
[ -f "$CP_FILE" ] || wget -q -O "$CP_FILE" "$CODEPOINTS_URL"
echo "  Downloaded full font: $(du -h "$MS_FULL" | cut -f1)"

# woff2 → ttf (fontTools 读取 cmap 用, 同时供后续子集化)
python3 -c "
from fontTools.ttLib import TTFont
font = TTFont('$MS_FULL')
font.flavor = None
font.save('$MS_TTF')
"

# 解析 codepoint: 优先用上游 codepoints 文件; 若该编码在字体 cmap 中不存在,
# 则按字形名回退到字体实际编码并告警 (上游文件偶有滞后, 如 movie e684 实际为 e404,
# 直接信任会导致 pyftsubset 静默丢字形、页面渲染空白)。
# 清单里的名字若在字体中完全找不到, 说明拼写错误或图标已从上游移除, 直接失败。
RESOLVED_FILE="/tmp/ms-icons-resolved.tsv"
python3 - "$CP_FILE" "$MS_TTF" "$ICONS_TMP" "$RESOLVED_FILE" <<'PYEOF'
import sys
from fontTools.ttLib import TTFont

cp_file, ttf_path, icons_path, resolved_path = sys.argv[1:5]

declared = {}
with open(cp_file) as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) == 2:
            declared[parts[0]] = parts[1]

cmap = TTFont(ttf_path).getBestCmap()
glyph_cps = {}
for codepoint, glyph in cmap.items():
    glyph_cps.setdefault(glyph, []).append(codepoint)

icons = [line.strip() for line in open(icons_path) if line.strip()]
resolved = {}
warnings = []
missing = []
for name in icons:
    hexcp = declared.get(name)
    codepoint = int(hexcp, 16) if hexcp else None
    if codepoint is not None and codepoint in cmap:
        resolved[name] = hexcp
        continue
    candidates = glyph_cps.get(name)
    if candidates:
        chosen = max(candidates)
        resolved[name] = f'{chosen:04x}'
        warnings.append(f'{name}: {hexcp or "(none)"} -> {chosen:04x}')
    else:
        missing.append(name)

if missing:
    print('[ERROR] icons.txt 中以下图标名在 Material Symbols 中不存在, 请检查拼写:',
          ', '.join(sorted(missing)), file=sys.stderr)
    sys.exit(1)

with open(resolved_path, 'w') as out:
    for name in sorted(resolved):
        out.write(f'{name} {resolved[name]}\n')
for w in warnings:
    print(f'  [WARN] codepoint corrected: {w}')
PYEOF

UNICODES=$(awk '{printf ",U+%s", $2}' "$RESOLVED_FILE")
UNICODES="${UNICODES#,}"
UNICODE_COUNT=$(wc -l < "$RESOLVED_FILE")
echo "  Icons: ${ICON_COUNT}, Unicodes: ${UNICODE_COUNT}"

# ── 2a. 生成 codepoint 映射 (MsIcon 用 codepoint 渲染，无需 ligature) ──
CODEPOINT_FILE="$SRC_DIR/config/icon-codepoints.ts"
python3 - "$RESOLVED_FILE" "$CODEPOINT_FILE" <<'PYEOF'
import sys

resolved_path, out_path = sys.argv[1:3]
entries = []
with open(resolved_path) as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) == 2:
            entries.append((parts[0], parts[1]))

with open(out_path, 'w') as out:
    out.write('// Auto-generated by build-fonts.sh — DO NOT EDIT\n')
    out.write('export const ICON_CODEPOINTS = {\n')
    for name, cp in sorted(entries):
        out.write("  '%s': '\\u%s',\n" % (name, cp))
    out.write('} as const\n\n')
    out.write('export type IconName = keyof typeof ICON_CODEPOINTS\n')
PYEOF
echo "  Generated: $(basename "$CODEPOINT_FILE") (${UNICODE_COUNT} entries)"

mkdir -p "$FONTS_DIR"
pyftsubset "$MS_TTF" \
    --unicodes="$UNICODES" \
    --layout-features='*' \
    --flavor=woff2 \
    --output-file="$MS_OUTPUT"

echo "  Subset: $(du -h "$MS_OUTPUT" | cut -f1) (from $(du -h "$MS_FULL" | cut -f1))"
echo "=== Done ==="
